(require htdp/testing)

(load "EECS345_Part3.rkt")

;Part 1
;(check-expect (interpret "tests/Part1Test1.rkt") 150)
;(check-expect (interpret "tests/Part1Test2.rkt") -4)
;(check-expect (interpret "tests/Part1Test3.rkt") 10)
;(check-expect (interpret "tests/Part1Test4.rkt") 16)
;(check-expect (interpret "tests/Part1Test5.rkt") 220)
;(check-expect (interpret "tests/Part1Test6.rkt") 5)
;(check-expect (interpret "tests/Part1Test7.rkt") 6)
;(check-expect (interpret "tests/Part1Test8.rkt") 10)
;(check-expect (interpret "tests/Part1Test9.rkt") 5)
;(check-expect (interpret "tests/Part1Test10.rkt") -39)
;(check-error (interpret "tests/Part1Test11.rkt") "unknown: variable not declared")
;(check-error (interpret "tests/Part1Test12.rkt") "unknown: variable not declared")
;(check-error (interpret "tests/Part1Test13.rkt") "using before assigning")
;(check-error (interpret "tests/Part1Test14.rkt") "variable already declared")
;(check-expect (interpret "tests/Part1Test15.rkt") 'true)
;(check-expect (interpret "tests/Part1Test16.rkt") 100)
;(check-expect (interpret "tests/Part1Test17.rkt") 'false)
;(check-expect (interpret "tests/Part1Test18.rkt") 'true)
;(check-expect (interpret "tests/Part1Test19.rkt") 128)
;(check-expect (interpret "tests/Part1Test20.rkt") 12)

;Part 2
;(check-expect (interpret "tests/Part2Test1.rkt") 20)
;(check-expect (interpret "tests/Part2Test2.rkt") 164)
;(check-expect (interpret "tests/Part2Test3.rkt") 32)
;(check-expect (interpret "tests/Part2Test4.rkt") 2)
;(check-expect (interpret "tests/Part2Test5.rkt") 'undefined)
;(check-expect (interpret "tests/Part2Test6.rkt") 25)
;(check-expect (interpret "tests/Part2Test7.rkt") 21)
;(check-expect (interpret "tests/Part2Test8.rkt") 6)
;(check-expect (interpret "tests/Part2Test9.rkt") -1)
;(check-expect (interpret "tests/Part2Test10.rkt") 789)
;(check-error (interpret "tests/Part2Test11.rkt") "unknown: variable not declared")
;(check-error (interpret "tests/Part2Test12.rkt") "unknown: variable not declared")
;(check-error (interpret "tests/Part2Test13.rkt") "illegal break")
;(check-expect (interpret "tests/Part2Test14.rkt") 12)
;(check-expect (interpret "tests/Part2Test15.rkt") 125)
;(check-expect (interpret "tests/Part2Test16.rkt") 110)
;(check-expect (interpret "tests/Part2Test17.rkt") 2000400)
;(check-expect (interpret "tests/Part2Test18.rkt") 101)
;(check-error (interpret "tests/Part2Test19.rkt") "no where to throw")

;Part 3
;(check-expect (interpret "tests/Part3Test1.rkt") 10)
;(check-expect (interpret "tests/Part3Test2.rkt") 14)
;(check-expect (interpret "tests/Part3Test3.rkt") 45)
;(check-expect (interpret "tests/Part3Test4.rkt") 55)
;(check-expect (interpret "tests/Part3Test5.rkt") 1)
;(check-expect (interpret "tests/Part3Test6.rkt") 115)
;(check-expect (interpret "tests/Part3Test7.rkt") 'true)
;(check-expect (interpret "tests/Part3Test8.rkt") 20)
;(check-expect (interpret "tests/Part3Test9.rkt") 24)
;(check-expect (interpret "tests/Part3Test10.rkt") 2) 
;(check-expect (interpret "tests/Part3Test11.rkt") 35)
;(check-error (interpret "tests/Part3Test12.rkt") "Mismatched Parameters")
;(check-expect (interpret "tests/Part3Test13.rkt") 90)
;(check-expect (interpret "tests/Part3Test14.rkt") 69)
;(check-expect (interpret "tests/Part3Test15.rkt") 87)
;(check-expect (interpret "tests/Part3Test16.rkt") 64)
;(check-error (interpret "tests/Part3Test17.rkt") "unknown: variable not declared")
;(check-expect (interpret "tests/Part3Test18.rkt") 125)
;(check-expect (interpret "tests/Part3Test19.rkt") 100)
;(check-expect (interpret "tests/Part3Test20.rkt") 2000400)

;Part 4
;(check-expect (interpret "tests/Part4Test1.rkt" "A") 15)
;(check-expect (interpret "tests/Part4Test2.rkt" "A") 12)
;(check-expect (interpret "tests/Part4Test3.rkt" "A") 125)
;(check-expect (interpret "tests/Part4Test4.rkt" "A") 36)
;(check-expect (interpret "tests/Part4Test5.rkt" "A") 54)
;(check-expect (interpret "tests/Part4Test6.rkt" "A") 110)
;(check-expect (interpret "tests/Part4Test7.rkt" "C") 26)
;(check-expect (interpret "tests/Part4Test8.rkt" "Square") 117)
;(check-expect (interpret "tests/Part4Test9.rkt" "Square") 32)
;(check-expect (interpret "tests/Part4Test10.rkt" "List") 15) 
;(check-expect (interpret "tests/Part4Test11.rkt" "List") 123456)
;(check-expect (interpret "tests/Part4Test12.rkt" "List") 5285)
;(check-expect (interpret "tests/Part4Test13.rkt" "C") -716)

(generate-report)